### ISSUE TITLE
v0.1 Roadmap

### ISSUE THREAD

**Issue by yxonic** [yxonic/rcommunity#1]
# Goal

## Vision of this project

- A NoSQL database specifically designed for building community systems around current business.
- Provide a type-safe intuitive API based on **reactions** for highly customizable community actions and queries.
- Use a K-V database as storage layer for better consistency and scalability.

## Main objectives

- Community service building:
  - [ ] Support different reaction types including like, vote, comment, etc.
  - [ ] Support operations including set, unset, push, remove last, remove all, edit content, etc.
  - [ ] Support listings, statistics, and sorting by time/count/sum for reactions of user/item.
- Type-safe API:
  - [ ] Compile-time assurance and constraints: typed data keys, statistic, listing and sorting functionalities.
  - [ ] Typed data keys: use `User(1000)`, `Comment(2000)` instead of just `1000`, `2000`, to avoid confusion and misuse of data keys of different types.
  - [ ] Split user/item/reaction data keys and values. Attach data values to keys through `WithData<T>` trait.
  - [ ] Statistics and listings: different type of reactions should support different set of queries. E.g. numerical reactions can have sum, and enumerable reactions can have listings and statistics per reaction enumeration. Reaction types are annotated through traits.
  - [ ] Check if sorting key is possible statically. Operations and caching are implemented as runtime features.
  - [ ] CRUD: generate different behaviors according to traits with macros. Or, learn and use specialization.
- Optimized to community data characteristics:
  - [ ] Efficient data, codec, and index design for data storage.
  - [ ] Well-designed transactions considering weak dependencies among reactions.
  - [ ] Sort result caching: decide a temporary or permanent index on runtime.

# Implementation

## API design

- [ ] Traits for user, item & reaction.
- [ ] Traits for different reaction types.
- [ ] Update index on add or remove based on trait labels: use specialization.
- [ ] Derive macros.
- [ ] Macro/codegen for generating named methods.

## Key-value scheme
- [x] Strings, floats, etc. encoding.
- [ ] Indexes.
- [ ] Metadata.
- [ ] Reaction data.

## Operations
- [ ] Add & remove.
- [ ] Stat queries.
- [ ] List queries.
- [ ] List and fetch.
- [ ] Sort (and fetch).

## Development & Debugging
- [x] Clippy lints: warn pedantic.
- [ ] Testing: trait soundness test, correctness test with a mocking backend.
- [ ] Benchmarking: throughput, read/write factor, etc.

## Release
